<?php
require_once('2048_fns.php');
session_start();
srand(time());
$text=RandomPass(6);
$_SESSION['captcha']=$text;
$height=50;
$width=150;
$im=imagecreatetruecolor($width,$height);
$black=imagecolorallocate($im,rand(0,100),rand(0,100),rand(0,100));
imagefill($im,0,0,$black);
$width_image=imagesx($im);
$height_image=imagesy($im);
$font_size=15;
putenv('GDFONTPATH=/home/a2480859/public_html/');
$font_name='arial.ttf';
$white=imagecolorallocate($im,rand(100,255),rand(100,255),rand(100,255));
imageline($im,rand(0,$width/2),rand(0,$height),$width,rand(0,$height),$white);
imageline($im,0,rand(0,$height),$width,rand(0,$height),$white);
imageline($im,0,rand(0,$height),rand($width/2,$width),rand(0,$height),$white);
$dim=array(0,0,0,0,0,0,0,0);
for($i=0;$i<6;$i++)
{
$angle=rand(-60,60);
$letter_width=$dim[2]-$dim[0];
$x+=$letter_width+10;
$y=rand(20,40);
$dim=imagettfbbox($font_size,$angle,$font_name,$text[$i]);
imagettftext($im,$font_size,$angle,$x,$y,$white,$font_name,$text[$i]);
}
header('Content-type: image/png');
imagepng($im);
imagedestroy($im);
?>